# app/api/chat_knowledge.py
"""
Local knowledge base for the DataStats application.
Provides precise, ready-to-use answers for chatbot queries.
"""

from difflib import get_close_matches

# === Core knowledge base ===
KNOWLEDGE = {
    "about": (
        "DataStats is a professional in-house data analysis web application built "
        "for the Central Bank (BEAC/CNEF). It enables analysts, economists, and researchers "
        "to upload datasets, perform statistical analyses, generate visualizations, "
        "and download reports. It’s built with Flask, MySQL, HTML/CSS/JS, and Python analytical engines."
    ),

    "roles": (
        "The application defines three main user roles:\n"
        "• **Analyst** – Can upload datasets, perform analyses, and visualize results.\n"
        "• **Viewer** – Can explore, search, and view analyses generated by analysts.\n"
        "• **Admin** – Manages accounts, user permissions, and monitors platform activity."
    ),

    "features": (
        "DataStats supports data cleaning, descriptive and inferential statistics, "
        "dimensionality reduction (PCA/MCA), regression models, non-parametric ML models "
        "(Random Forest, KNN), clustering (KMeans, Hierarchical), time series forecasting (ARIMA), "
        "and correlation/matrix analysis. It also includes visualization and report export (PDF, CSV)."
    ),

    "technology_stack": (
        "DataStats is developed using Flask (Python) for the backend, MySQL as the database, "
        "and HTML/CSS/JavaScript for the frontend. The app uses SQLAlchemy ORM, Flask-Login for "
        "authentication, Flask-Migrate for migrations, and OpenAI API for the integrated chatbot."
    ),

    "folder_structure": (
        "The DataStats project is organized into modular components:\n"
        "• `/app/` – Core logic, routes, models, blueprints (auth, main, analyst, viewer, api)\n"
        "• `/analysis_engine/` – Analytical modules: statistics, regression, clustering, etc.\n"
        "• `/static/` – Frontend assets (CSS, JS, images)\n"
        "• `/templates/` – Jinja2 HTML templates for each blueprint\n"
        "• `/uploads/` – Uploaded datasets\n"
        "• `/migrations/` – Database migrations"
    ),

    "analyst": (
        "The Analyst role allows users to upload datasets, clean data, perform analyses, "
        "and generate visualizations such as histograms, scatter plots, PCA, clustering, and regressions. "
        "Results are stored in the database and can be shared with viewers."
    ),

    "viewer": (
        "The Viewer role focuses on exploring results. Viewers can access dashboards, search and view "
        "graphs, review analysis insights, and monitor trends without editing data."
    ),

    "data_storage": (
        "Uploaded datasets are stored in the `/uploads/` directory, while metadata and analysis results "
        "are recorded in the MySQL database through SQLAlchemy models. Visualizations are stored as images "
        "or base64 objects depending on analysis type."
    ),

    "security": (
        "The app enforces authentication with Flask-Login, uses CSRF protection, and role-based access control. "
        "Sensitive routes and API endpoints are restricted by user role."
    ),

    "chatbot": (
        "The integrated chatbot assists users in understanding DataStats’ features, guiding analyses, "
        "and providing explanations about statistical methods and system usage. It prioritizes internal knowledge "
        "before calling the OpenAI API."
    ),
}


# === Helper functions ===
def get_local_answer(question: str) -> str | None:
    """
    Try to match the user question with the local DataStats knowledge base.
    Returns a predefined answer or None if not found.
    """
    question_lower = question.lower()

    # Direct keyword match
    for key, answer in KNOWLEDGE.items():
        if key in question_lower:
            return answer

    # Fuzzy match (e.g., “how does datastats work?”)
    keys = list(KNOWLEDGE.keys())
    best_match = get_close_matches(question_lower, keys, n=1, cutoff=0.5)
    if best_match:
        return KNOWLEDGE[best_match[0]]

    # Broad category match
    if any(word in question_lower for word in ["what is datastats", "about datastats", "purpose"]):
        return KNOWLEDGE["about"]

    if "structure" in question_lower or "folders" in question_lower:
        return KNOWLEDGE["folder_structure"]

    return None
